name: "Test App"
on: [push, pull_request]

jobs:
  run_tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        run: |
          sudo apt-get install -y --no-install-recommends \
            python3 python3-pip python-is-python3

      - name: Install Python Packages
        run: |
          python -m pip install -r app/requirements.txt

      - name: Run Tests
        run: |
          cd app
          python -m pytest
